- Target: nmaguiar/nearless:build (alpine 3.22.0_alpha20250108)
  Class: os-pkgs
  Type: alpine
  Vulnerabilities:
  - VulnerabilityID: CVE-2025-4575
    PkgID: libcrypto3@3.5.0-r0
    PkgName: libcrypto3
    PkgIdentifier:
      PURL: pkg:apk/alpine/libcrypto3@3.5.0-r0?arch=x86_64&distro=3.22.0_alpha20250108
      UID: 7d0909ac596ece41
    InstalledVersion: 3.5.0-r0
    FixedVersion: 3.5.1-r0
    Status: fixed
    Layer:
      Digest: sha256:a27a8a9dc0887cc3eab7a59aa90a09ca17fd1220b8f4feddad48e177fe87c08d
      DiffID: sha256:f015acec4aa423e9383d631df1d9e132ea1d77b74ff1c7b7009a22d8bb3ac1fa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-4575
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: Use of -addreject option with the openssl x509 applicat ...'
    Description: |-
      Issue summary: Use of -addreject option with the openssl x509 application adds
      a trusted use instead of a rejected use for a certificate.

      Impact summary: If a user intends to make a trusted certificate rejected for
      a particular use it will be instead marked as trusted for that use.

      A copy & paste error during minor refactoring of the code introduced this
      issue in the OpenSSL 3.5 version. If, for example, a trusted CA certificate
      should be trusted only for the purpose of authenticating TLS servers but not
      for CMS signature verification and the CMS signature verification is intended
      to be marked as rejected with the -addreject option, the resulting CA
      certificate will be trusted for CMS signature verification purpose instead.

      Only users which use the trusted certificate format who use the openssl x509
      command line application to add rejected uses are affected by this issue.
      The issues affecting only the command line application are considered to
      be Low severity.

      The FIPS modules in 3.5, 3.4, 3.3, 3.2, 3.1 and 3.0 are not affected by this
      issue.

      OpenSSL 3.4, 3.3, 3.2, 3.1, 3.0, 1.1.1 and 1.0.2 are also not affected by this
      issue.
    Severity: UNKNOWN
    CweIDs:
    - CWE-295
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/22/1
    - https://github.com/openssl/openssl/commit/e96d22446e633d117e6c9904cb15b4693e956eaa
    - https://openssl-library.org/news/secadv/20250522.txt
    PublishedDate: '2025-05-22T14:16:07.63Z'
    LastModifiedDate: '2025-05-23T15:55:02.04Z'
  - VulnerabilityID: CVE-2025-4575
    PkgID: libssl3@3.5.0-r0
    PkgName: libssl3
    PkgIdentifier:
      PURL: pkg:apk/alpine/libssl3@3.5.0-r0?arch=x86_64&distro=3.22.0_alpha20250108
      UID: efca7f64074c24b8
    InstalledVersion: 3.5.0-r0
    FixedVersion: 3.5.1-r0
    Status: fixed
    Layer:
      Digest: sha256:a27a8a9dc0887cc3eab7a59aa90a09ca17fd1220b8f4feddad48e177fe87c08d
      DiffID: sha256:f015acec4aa423e9383d631df1d9e132ea1d77b74ff1c7b7009a22d8bb3ac1fa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-4575
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: Use of -addreject option with the openssl x509 applicat ...'
    Description: |-
      Issue summary: Use of -addreject option with the openssl x509 application adds
      a trusted use instead of a rejected use for a certificate.

      Impact summary: If a user intends to make a trusted certificate rejected for
      a particular use it will be instead marked as trusted for that use.

      A copy & paste error during minor refactoring of the code introduced this
      issue in the OpenSSL 3.5 version. If, for example, a trusted CA certificate
      should be trusted only for the purpose of authenticating TLS servers but not
      for CMS signature verification and the CMS signature verification is intended
      to be marked as rejected with the -addreject option, the resulting CA
      certificate will be trusted for CMS signature verification purpose instead.

      Only users which use the trusted certificate format who use the openssl x509
      command line application to add rejected uses are affected by this issue.
      The issues affecting only the command line application are considered to
      be Low severity.

      The FIPS modules in 3.5, 3.4, 3.3, 3.2, 3.1 and 3.0 are not affected by this
      issue.

      OpenSSL 3.4, 3.3, 3.2, 3.1, 3.0, 1.1.1 and 1.0.2 are also not affected by this
      issue.
    Severity: UNKNOWN
    CweIDs:
    - CWE-295
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/22/1
    - https://github.com/openssl/openssl/commit/e96d22446e633d117e6c9904cb15b4693e956eaa
    - https://openssl-library.org/news/secadv/20250522.txt
    PublishedDate: '2025-05-22T14:16:07.63Z'
    LastModifiedDate: '2025-05-23T15:55:02.04Z'
  - VulnerabilityID: CVE-2025-26519
    PkgID: musl@1.2.5-r9
    PkgName: musl
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl@1.2.5-r9?arch=x86_64&distro=3.22.0_alpha20250108
      UID: ebcbb7de0538c04f
    InstalledVersion: 1.2.5-r9
    FixedVersion: 1.2.5-r10
    Status: fixed
    Layer:
      Digest: sha256:a27a8a9dc0887cc3eab7a59aa90a09ca17fd1220b8f4feddad48e177fe87c08d
      DiffID: sha256:f015acec4aa423e9383d631df1d9e132ea1d77b74ff1c7b7009a22d8bb3ac1fa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-26519
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write ...
    Description: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write vulnerability when an attacker can trigger iconv conversion of untrusted EUC-KR text to UTF-8.
    Severity: UNKNOWN
    CweIDs:
    - CWE-787
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/13/2
    - http://www.openwall.com/lists/oss-security/2025/02/13/3
    - http://www.openwall.com/lists/oss-security/2025/02/13/4
    - http://www.openwall.com/lists/oss-security/2025/02/13/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/6
    - https://git.musl-libc.org/cgit/musl/commit/?id=c47ad25ea3b484e10326f933e927c0bc8cded3da
    - https://git.musl-libc.org/cgit/musl/commit/?id=e5adcd97b5196e29991b524237381a0202a60659
    - https://www.openwall.com/lists/oss-security/2025/02/13/2
    PublishedDate: '2025-02-14T04:15:09.05Z'
    LastModifiedDate: '2025-02-14T17:15:23.09Z'
  - VulnerabilityID: CVE-2025-26519
    PkgID: musl-utils@1.2.5-r9
    PkgName: musl-utils
    PkgIdentifier:
      PURL: pkg:apk/alpine/musl-utils@1.2.5-r9?arch=x86_64&distro=3.22.0_alpha20250108
      UID: 8b959e5d6017bacb
    InstalledVersion: 1.2.5-r9
    FixedVersion: 1.2.5-r10
    Status: fixed
    Layer:
      Digest: sha256:a27a8a9dc0887cc3eab7a59aa90a09ca17fd1220b8f4feddad48e177fe87c08d
      DiffID: sha256:f015acec4aa423e9383d631df1d9e132ea1d77b74ff1c7b7009a22d8bb3ac1fa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-26519
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write ...
    Description: musl libc 0.9.13 through 1.2.5 before 1.2.6 has an out-of-bounds write vulnerability when an attacker can trigger iconv conversion of untrusted EUC-KR text to UTF-8.
    Severity: UNKNOWN
    CweIDs:
    - CWE-787
    References:
    - http://www.openwall.com/lists/oss-security/2025/02/13/2
    - http://www.openwall.com/lists/oss-security/2025/02/13/3
    - http://www.openwall.com/lists/oss-security/2025/02/13/4
    - http://www.openwall.com/lists/oss-security/2025/02/13/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/5
    - http://www.openwall.com/lists/oss-security/2025/02/14/6
    - https://git.musl-libc.org/cgit/musl/commit/?id=c47ad25ea3b484e10326f933e927c0bc8cded3da
    - https://git.musl-libc.org/cgit/musl/commit/?id=e5adcd97b5196e29991b524237381a0202a60659
    - https://www.openwall.com/lists/oss-security/2025/02/13/2
    PublishedDate: '2025-02-14T04:15:09.05Z'
    LastModifiedDate: '2025-02-14T17:15:23.09Z'
  - VulnerabilityID: CVE-2025-4575
    PkgID: openssl@3.5.0-r0
    PkgName: openssl
    PkgIdentifier:
      PURL: pkg:apk/alpine/openssl@3.5.0-r0?arch=x86_64&distro=3.22.0_alpha20250108
      UID: 23c6aecba9792985
    InstalledVersion: 3.5.0-r0
    FixedVersion: 3.5.1-r0
    Status: fixed
    Layer:
      Digest: sha256:a27a8a9dc0887cc3eab7a59aa90a09ca17fd1220b8f4feddad48e177fe87c08d
      DiffID: sha256:f015acec4aa423e9383d631df1d9e132ea1d77b74ff1c7b7009a22d8bb3ac1fa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-4575
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'Issue summary: Use of -addreject option with the openssl x509 applicat ...'
    Description: |-
      Issue summary: Use of -addreject option with the openssl x509 application adds
      a trusted use instead of a rejected use for a certificate.

      Impact summary: If a user intends to make a trusted certificate rejected for
      a particular use it will be instead marked as trusted for that use.

      A copy & paste error during minor refactoring of the code introduced this
      issue in the OpenSSL 3.5 version. If, for example, a trusted CA certificate
      should be trusted only for the purpose of authenticating TLS servers but not
      for CMS signature verification and the CMS signature verification is intended
      to be marked as rejected with the -addreject option, the resulting CA
      certificate will be trusted for CMS signature verification purpose instead.

      Only users which use the trusted certificate format who use the openssl x509
      command line application to add rejected uses are affected by this issue.
      The issues affecting only the command line application are considered to
      be Low severity.

      The FIPS modules in 3.5, 3.4, 3.3, 3.2, 3.1 and 3.0 are not affected by this
      issue.

      OpenSSL 3.4, 3.3, 3.2, 3.1, 3.0, 1.1.1 and 1.0.2 are also not affected by this
      issue.
    Severity: UNKNOWN
    CweIDs:
    - CWE-295
    References:
    - http://www.openwall.com/lists/oss-security/2025/05/22/1
    - https://github.com/openssl/openssl/commit/e96d22446e633d117e6c9904cb15b4693e956eaa
    - https://openssl-library.org/news/secadv/20250522.txt
    PublishedDate: '2025-05-22T14:16:07.63Z'
    LastModifiedDate: '2025-05-23T15:55:02.04Z'
  - VulnerabilityID: CVE-2025-32462
    PkgID: sudo@1.9.17-r0
    PkgName: sudo
    PkgIdentifier:
      PURL: pkg:apk/alpine/sudo@1.9.17-r0?arch=x86_64&distro=3.22.0_alpha20250108
      UID: 1f891adb10dfe01d
    InstalledVersion: 1.9.17-r0
    FixedVersion: 1.9.17_p1-r0
    Status: fixed
    Layer:
      Digest: sha256:a27a8a9dc0887cc3eab7a59aa90a09ca17fd1220b8f4feddad48e177fe87c08d
      DiffID: sha256:f015acec4aa423e9383d631df1d9e132ea1d77b74ff1c7b7009a22d8bb3ac1fa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-32462
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'sudo: LPE via host option'
    Description: Sudo before 1.9.17p1, when used with a sudoers file that specifies a host that is neither the current host nor ALL, allows listed users to execute commands on unintended machines.
    Severity: HIGH
    CweIDs:
    - CWE-863
    VendorSeverity:
      alma: 3
      oracle-oval: 3
      photon: 1
      redhat: 3
      ubuntu: 3
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H
        V3Score: 7
    References:
    - https://access.redhat.com/errata/RHSA-2025:9978
    - https://access.redhat.com/security/cve/CVE-2025-32462
    - https://bugzilla.redhat.com/2374692
    - https://errata.almalinux.org/9/ALSA-2025-9978.html
    - https://linux.oracle.com/cve/CVE-2025-32462.html
    - https://linux.oracle.com/errata/ELSA-2025-9978.html
    - https://nvd.nist.gov/vuln/detail/CVE-2025-32462
    - https://ubuntu.com/security/notices/USN-7604-1
    - https://ubuntu.com/security/notices/USN-7604-2
    - https://www.cve.org/CVERecord?id=CVE-2025-32462
    - https://www.openwall.com/lists/oss-security/2025/06/30/2
    - https://www.stratascale.com/vulnerability-alert-CVE-2025-32462-sudo-host
    - https://www.sudo.ws/releases/changelog/
    - https://www.sudo.ws/security/advisories/
    - https://www.sudo.ws/security/advisories/host_any/
    PublishedDate: '2025-06-30T21:15:30.08Z'
    LastModifiedDate: '2025-07-03T15:14:12.767Z'
  - VulnerabilityID: CVE-2025-32463
    PkgID: sudo@1.9.17-r0
    PkgName: sudo
    PkgIdentifier:
      PURL: pkg:apk/alpine/sudo@1.9.17-r0?arch=x86_64&distro=3.22.0_alpha20250108
      UID: 1f891adb10dfe01d
    InstalledVersion: 1.9.17-r0
    FixedVersion: 1.9.17_p1-r0
    Status: fixed
    Layer:
      Digest: sha256:a27a8a9dc0887cc3eab7a59aa90a09ca17fd1220b8f4feddad48e177fe87c08d
      DiffID: sha256:f015acec4aa423e9383d631df1d9e132ea1d77b74ff1c7b7009a22d8bb3ac1fa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-32463
    DataSource:
      ID: alpine
      Name: Alpine Secdb
      URL: https://secdb.alpinelinux.org/
    Title: 'sudo: LPE via chroot option'
    Description: Sudo before 1.9.17p1 allows local users to obtain root access because /etc/nsswitch.conf from a user-controlled directory is used with the --chroot option.
    Severity: HIGH
    CweIDs:
    - CWE-829
    VendorSeverity:
      photon: 4
      redhat: 3
      ubuntu: 3
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
        V3Score: 7.8
    References:
    - https://access.redhat.com/security/cve/CVE-2025-32463
    - https://access.redhat.com/security/cve/cve-2025-32463
    - https://bugs.gentoo.org/show_bug.cgi?id=CVE-2025-32463
    - https://explore.alas.aws.amazon.com/CVE-2025-32463.html
    - https://nvd.nist.gov/vuln/detail/CVE-2025-32463
    - https://security-tracker.debian.org/tracker/CVE-2025-32463
    - https://ubuntu.com/security/notices/USN-7604-1
    - https://www.cve.org/CVERecord?id=CVE-2025-32463
    - https://www.openwall.com/lists/oss-security/2025/06/30/3
    - https://www.stratascale.com/vulnerability-alert-CVE-2025-32463-sudo-chroot
    - https://www.sudo.ws/releases/changelog/
    - https://www.sudo.ws/security/advisories/
    - https://www.sudo.ws/security/advisories/chroot_bug/
    - https://www.suse.com/security/cve/CVE-2025-32463.html
    - https://www.suse.com/support/update/announcement/2025/suse-su-202502177-1/
    PublishedDate: '2025-06-30T21:15:30.257Z'
    LastModifiedDate: '2025-07-03T15:14:12.767Z'
- Target: Java
  Class: lang-pkgs
  Type: jar
