- Target: nmaguiar/nearless:build (alpine 3.20.3)
  Class: os-pkgs
  Type: alpine
- Target: Java
  Class: lang-pkgs
  Type: jar
  Vulnerabilities:
  - VulnerabilityID: CVE-2023-3635
    PkgName: com.squareup.okio:okio
    PkgPath: openaf/Kube/okio-1.15.0.jar
    PkgIdentifier:
      PURL: pkg:maven/com.squareup.okio/okio@1.15.0
      UID: 54d0708001bc0aec
    InstalledVersion: 1.15.0
    FixedVersion: 3.4.0, 1.17.6
    Status: fixed
    Layer:
      Digest: sha256:c2b43e4b0dc880ff9c7ede08697ef6f2f19a8b8280e190e83dea42ead28f4945
      DiffID: sha256:0a66dd6173e3f283caac3a18ee0fa18eb3c9394110b2efec5cf8c6cf1df859f0
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2023-3635
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Maven
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Amaven
    Title: 'okio: GzipSource class improper exception handling'
    Description: |+
      GzipSource does not handle an exception that might be raised when parsing a malformed gzip buffer. This may lead to denial of service of the Okio client when handling a crafted GZIP archive, by using the GzipSource class.

    Severity: MEDIUM
    CweIDs:
    - CWE-681
    - CWE-195
    VendorSeverity:
      ghsa: 2
      nvd: 3
      redhat: 3
    CVSS:
      ghsa:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 5.9
      nvd:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
    References:
    - https://access.redhat.com/security/cve/CVE-2023-3635
    - https://github.com/square/okio
    - https://github.com/square/okio/blob/master/CHANGELOG.md#version-1176
    - https://github.com/square/okio/commit/81bce1a30af244550b0324597720e4799281da7b
    - https://github.com/square/okio/commit/b4fa875dc24950680c386e4b1c593660ce4f7839
    - https://github.com/square/okio/pull/1280
    - https://github.com/square/okio/pull/1334
    - https://nvd.nist.gov/vuln/detail/CVE-2023-3635
    - https://research.jfrog.com/vulnerabilities/okio-gzip-source-unhandled-exception-dos-xray-523195
    - https://research.jfrog.com/vulnerabilities/okio-gzip-source-unhandled-exception-dos-xray-523195/
    - https://www.cve.org/CVERecord?id=CVE-2023-3635
    PublishedDate: '2023-07-12T19:15:08.983Z'
    LastModifiedDate: '2023-10-25T15:17:42.17Z'
