jobs:
# -------------------------------
- name: Prepare scheduled trigger
  # type: periodic
  # typeArgs:
  #   timeInterval: 2500
  ##   cron: '*/5 * * * * *'  
  # exec: |
  #   print("!!!")

# ------------------------
- name: Trigger chat.ncasa
  exec: |
    args._output = ow.server.httpd.reply("OK!")