jobs:
# ------------------
- name: Prepare init

# -------------------------------
- name: Prepare scheduled trigger
  # type: periodic
  # typeArgs:
  #   timeInterval: 2500
  ##   cron: '*/5 * * * * *'  
  # exec: |
  #   print("!!!")

# -----------------------
- name: Trigger openaf.io
  exec: |
    args._output = ow.server.httpd.reply("OK!\n")

# ---------------------
- name: Trigger anysite
  exec: |
    args._output = ow.server.httpd.reply("OK (this is for " + args._host + ")")